Repository dlang-community/libdparse, pull requests merged in 2018-10, with the labels that each got.

#279 fix #278 - Infinite loop with some ASM code
  src/dparse/parser.d
  test/fail_files/bad_asm.d
Labels: Bug Fix

#281 fix meson build by using the right library version
  meson.build
Labels: Bug Fix, auto-merge

#283 fix #282 - Function parameter attributes are ignored
  src/dparse/parser.d
Labels: Bug Fix, auto-merge, trivial

#290 fix #289 - Inconsistencies of IfStatement conditions
  src/dparse/ast.d
  src/dparse/formatter.d
  src/dparse/parser.d
  test/pass_files/ifConditions.d
  test/pass_files/statements.d
  test/pass_files/templates.d
Labels: Bug Fix

#284 Add support for new mixin syntax, close #280
  src/dparse/ast.d
  src/dparse/formatter.d
  src/dparse/parser.d
  test/pass_files/declarations.d
  test/pass_files/expressions.d
  test/pass_files/statements.d
Labels: auto-merge, auto-merge-squash, enhancement, parser

#293 Add a note mentioning dsymbol SimpleParser
  src/dparse/parser.d
Labels: auto-merge, trivial

#288 Add a ParserConfig struct, close #287
  src/dparse/ast.d
  src/dparse/formatter.d
  src/dparse/parser.d
  subprojects/stdx-allocator.wrap
  test/tester.d
Labels: auto-merge, enhancement

#295 temporarily prevent breakage in dsymbol
  src/dparse/parser.d
Labels: auto-merge, trivial

#296 fix missing default in old parseModule overloads
  src/dparse/parser.d
Labels: Bug Fix, auto-merge-squash, trivial

#297 fix overloads of parseModule ambiguity due to default param
  src/dparse/ast.d
  src/dparse/parser.d
Labels: auto-merge-squash
