Repository dlang-community/libdparse, pull requests merged in 2018-11, with the labels that each got.

#300 Prevent running CI twice when PR branch is in origin
  .travis.yml
  netlify.sh
Labels: auto-merge-squash

#302 Avoid more cases of possibly segaulting `current.type`
  src/dparse/parser.d
Labels: auto-merge-squash

#301 fixup #290, missed a case where rollback was possible, clocse #294
  src/dparse/parser.d
  test/fail_files/ifConditions.d
Labels: auto-merge-squash

#304 Implement DIP1009 correctly (#303)
  src/dparse/ast.d
  src/dparse/formatter.d
  src/dparse/parser.d
Labels: auto-merge-squash

#305 update meson version
  meson.build
Labels: auto-merge, trivial

#309 fix #307 - recently templatized parseModule is broken
  src/dparse/parser.d
Labels: Bug Fix, auto-merge-squash

#311 fix #306 again - if Conditions with a templatized type and no storage class
  src/dparse/parser.d
  test/pass_files/ifConditions.d
Labels: Bug Fix, auto-merge

#314 fix, dip 1009, semicolon as for "no body" is part of MissinFunctionBody rule
  src/dparse/parser.d
Labels: auto-merge

#317 fix #316 - Regression, function literal parsed as struct initializer
  src/dparse/ast.d
  src/dparse/parser.d
Labels: auto-merge-squash

#319 fix #318, segfault caused by structinit parsing
  src/dparse/ast.d
  src/dparse/parser.d
Labels: Bug Fix, auto-merge-squash

#320 fix possible formatting of a null block statement
  src/dparse/formatter.d
Labels: auto-merge
