Repository dlang-community/libdparse, pull requests merged in 2018-09, with the labels that each got.

#257 Add Meson build definition
  .travis.yml
  meson.build
  subprojects/stdx-allocator.wrap
Labels: auto-merge-squash

#271 improve parser coverage
  src/dparse/parser.d
  test/fail_files/misc_coverage.d
  test/pass_files/misc_coverage.d
Labels: auto-merge, enhancement, trivial

#273 provide token location to expression-based contracts
  src/dparse/parser.d
Labels: auto-merge

#275 fix #274 - Trailing semicolon of Expression-based invariant is seen as an empty statement
  src/dparse/parser.d
Labels: Bug Fix, auto-merge, trivial

#277 fix contract based invariant line usually offset by 1
  src/dparse/parser.d
Labels: Bug Fix, auto-merge
