Repository dlang-community/libdparse, pull requests merged in 2018-07, with the labels that each got.

#247 Fix #245: Range error with missing closing square bracket
  src/dparse/parser.d
  test/fail_files/issue245.d
Labels: Bug Fix, auto-merge, parser

#249 fix ddoc typo in returns section name
  src/std/experimental/lexer.d
Labels: auto-merge, trivial

#248 \s\body\do
  .travis.yml
  src/dparse/lexer.d
  src/dparse/parser.d
  src/dparse/rollback_allocator.d
Labels: auto-merge, trivial

#252 add a fake rule to test fix for GH page auto update
  src/dparse/parser.d
Labels: auto-merge
