Repository dlang-community/libdparse, pull requests merged in 2018-04, with the labels that each got.

#217 Allows incomplete switch statement, better for DCD
  src/dparse/parser.d
Labels: auto-merge, enhancement

#219 doc, add more missing special KW, sort them and fix a few tabs
  src/dparse/ast.d
  src/dparse/parser.d
Labels: auto-merge, trivial

#221 for DCD, return valid node on incomplete func call '(}'
  src/dparse/parser.d
Labels: auto-merge, enhancement

#222 update to stdx-allocator 2.77.1
  dub.json
Labels: auto-merge
