Repository dlang-community/libdparse, pull requests merged in 2018-05, with the labels that each got.

#229 fix #224 - Range violation for `/++`
  src/dparse/lexer.d
Labels: Bug Fix, auto-merge

#230 Always update the git submodules
  .travis.yml
Labels: auto-merge

#231 [trivial] Fix range violation error
  src/dparse/formatter.d
Labels: trivial

#234 Add start and end locations to DeclarationOrStatement
  src/dparse/ast.d
  src/dparse/parser.d
Labels: auto-merge, enhancement, trivial
