Repository dlang-community/libdparse, pull requests merged in 2019-01, with the labels that each got.

#335 fix #334 - literals with suffixes are reported as error when used as …
  src/dparse/parser.d
  test/pass_files/asm.d
Labels: Bug Fix, auto-merge-squash

#336 Remove "volatile" keyword
  src/dparse/lexer.d
  test/fuzzer.d
  test/tester.d
Labels: auto-merge-squash

#339 test/fuzzer: Fix compilation errors
  test/fuzzer.d
Labels: auto-merge-squash

#342 fix wrong rule in parseVariableDeclaration
  src/dparse/parser.d
Labels: auto-merge-squash, trivial

#343 fix #338 - A class Inheriting from an AliasSeq item is seen as an error
  src/dparse/parser.d
  test/fail_files/misc_coverage.d
  test/pass_files/classes.d
Labels: Bug Fix, auto-merge-squash, parser

#345 fix a range violation while formating ConditionalDeclaration
  src/dparse/formatter.d
Labels: auto-merge-squash
