Repository dlang-community/libdparse, pull requests merged in 2020-05, with the labels that each got.

#398 Fix #397 - extern(C++, ...) only supports identifiers
  src/dparse/ast.d
  src/dparse/parser.d
  test/pass_files/linkageAttributes.d
Labels: auto-merge

#400 Fix 394 - ///////////// comment lines wrongly interpreted as ddoc
  src/dparse/trivia.d
Labels: auto-merge

#401 Handle empty doc comments ("///") on unittests
  src/dparse/ast.d
  src/dparse/trivia.d
Labels: auto-merge

#402 Accept this as an asm operand
  src/dparse/parser.d
  test/pass_files/asm.d
Labels: auto-merge

#399 Fix 383 - Formatting AST including `@trusted` delegate produces inval…
  src/dparse/formatter.d
Labels: auto-merge

#404 Fix #53 - Support GDC extended asm syntax
  src/dparse/ast.d
  src/dparse/parser.d
  test/fail_files/asm-gcc.d
  test/pass_files/asm-gcc.d
Labels: auto-merge, enhancement, parser

#407 Use the LPAREN and RPAREN macros in gcc asm grammar
  src/dparse/parser.d
Labels: auto-merge, trivial

#411 fix tabs
  src/dparse/ast.d
  src/dparse/lexer.d
Labels: trivial

#414 Correctly treat 'export' as a protection attribute. Fix #413
  src/dparse/parser.d
  test/pass_files/issue0413.d
Labels: Bug Fix, auto-merge, parser
