Repository dlang-community/libdparse, pull requests merged in 2020-08, with the labels that each got.

#427 Fix 426: Storage classes for C style variadic functions
  src/dparse/ast.d
  src/dparse/parser.d
  test/fail_files/varargs-attributes.d
  test/pass_files/varargs-attributes.d
Labels: Bug Fix, auto-merge

#425 Add an XPath-based testing system for the AST generated by the parser
  .travis.yml
  src/dparse/astprinter.d
  test/ast_checks/file1.d
  test/ast_checks/file1.txt
  test/run_tests.sh
  test/tester.d
Labels: auto-merge, enhancement

#429 Fix #428
  src/dparse/astprinter.d
  src/dparse/parser.d
  test/ast_checks/issue428.d
  test/ast_checks/issue428.txt
Labels: Bug Fix, auto-merge

#432 Skip the AST checks when the tests are run by Buildkite.
  test/run_tests.sh
Labels: auto-merge

#435 Support user-defined attributes on module declarations
  src/dparse/ast.d
  src/dparse/parser.d
  test/ast_checks/moduleDec4.d
  test/ast_checks/moduleDec4.txt
  test/pass_files/moduleDec1.d
  test/pass_files/moduleDec2.d
  test/pass_files/moduleDec3.d
  test/pass_files/moduleDec4.d
  test/run_tests.sh
Labels: Bug Fix

#433 Add some functions that simplify token lookahead.
  src/dparse/parser.d
Labels: auto-merge, enhancement, parser
