Repository dlang-community/libdparse, pull requests merged in 2020-04, with the labels that each got.

#387 Whitespace and comment tokens
  meson.build
  src/dparse/lexer.d
  src/dparse/trivia.d
  src/std/experimental/lexer.d
Labels: auto-merge

#389 Fixed unittest on x86
  src/dparse/lexer.d
Labels: auto-merge, trivial

#391 Fix #390 - Error for opaque enum with base type
  src/dparse/parser.d
  test/pass_files/enums.d
Labels: auto-merge, bug, parser, trivial

#393 Make leading/trailing tokens array immutable
  src/dparse/lexer.d
Labels: auto-merge

#396 Fix #395 - Empty declaration for is(... == module), package, __vector + remove typedef
  src/dparse/parser.d
  test/pass_files/expressions.d
  test/pass_files/templates.d
Labels: auto-merge, parser, trivial
